/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author USER
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
          setTitle("Tela Principal");
         setLocationRelativeTo(null);
         setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBtnUsuarios = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBtnProdutos = new javax.swing.JButton();
        jBtnVendas = new javax.swing.JButton();
        jBtnConsulProduto = new javax.swing.JButton();
        jBtnConsulVendas = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        JMnuCadastros = new javax.swing.JMenu();
        jMnuUsuario = new javax.swing.JMenuItem();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        JMnuMovimentos = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMnuConsultas = new javax.swing.JMenu();
        JMnuConsulClientes = new javax.swing.JMenuItem();
        JMnuConsulIngredientes = new javax.swing.JMenuItem();
        JMnuConsulProdutos = new javax.swing.JMenuItem();
        JMnuConsulVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jBtnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/client32.png"))); // NOI18N
        jBtnUsuarios.setFocusable(false);
        jBtnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnUsuarios);

        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jBtnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/icons8-carrinho-de-compras-24.png"))); // NOI18N
        jBtnProdutos.setFocusable(false);
        jBtnProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnProdutos);

        jBtnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/produtos.png"))); // NOI18N
        jBtnVendas.setFocusable(false);
        jBtnVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendas);

        jBtnConsulProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/open-box.png"))); // NOI18N
        jBtnConsulProduto.setFocusable(false);
        jBtnConsulProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsulProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsulProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsulProdutoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsulProduto);

        jBtnConsulVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/trade.png"))); // NOI18N
        jBtnConsulVendas.setFocusable(false);
        jBtnConsulVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsulVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsulVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsulVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnConsulVendas);

        JMnuCadastros.setMnemonic('c');
        JMnuCadastros.setText("Cadastros");
        JMnuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnuCadastrosActionPerformed(evt);
            }
        });

        jMnuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/132244_unknown_person_icon.png"))); // NOI18N
        jMnuUsuario.setMnemonic('u');
        jMnuUsuario.setText("Usuários");
        jMnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarioActionPerformed(evt);
            }
        });
        JMnuCadastros.add(jMnuUsuario);

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/132301_list_clien_icon.png"))); // NOI18N
        jMnuClientes.setMnemonic('c');
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        JMnuCadastros.add(jMnuClientes);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/132341_dollar_financial_finance_banking_money_icon.png"))); // NOI18N
        jMnuProdutos.setMnemonic('p');
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        JMnuCadastros.add(jMnuProdutos);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/132300_open_file_icon.png"))); // NOI18N
        jMenuItem1.setMnemonic('i');
        jMenuItem1.setText("Ingredientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMnuCadastros.add(jMenuItem1);
        JMnuCadastros.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jMnuSair.setMnemonic('s');
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        JMnuCadastros.add(jMnuSair);

        jMenuBar3.add(JMnuCadastros);

        JMnuMovimentos.setText("Movimentos");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/132244_unknown_person_icon.png"))); // NOI18N
        jMnuVendas.setMnemonic('u');
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        JMnuMovimentos.add(jMnuVendas);

        jMenuBar3.add(JMnuMovimentos);

        jMnuConsultas.setText("Consultas");

        JMnuConsulClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        JMnuConsulClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/cliente_1.png"))); // NOI18N
        JMnuConsulClientes.setMnemonic('v');
        JMnuConsulClientes.setText("Clientes");
        JMnuConsulClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnuConsulClientesActionPerformed(evt);
            }
        });
        jMnuConsultas.add(JMnuConsulClientes);

        JMnuConsulIngredientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        JMnuConsulIngredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/groups32.png"))); // NOI18N
        JMnuConsulIngredientes.setMnemonic('v');
        JMnuConsulIngredientes.setText("Ingredientes");
        JMnuConsulIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnuConsulIngredientesActionPerformed(evt);
            }
        });
        jMnuConsultas.add(JMnuConsulIngredientes);

        JMnuConsulProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        JMnuConsulProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/produto_1.png"))); // NOI18N
        JMnuConsulProdutos.setMnemonic('v');
        JMnuConsulProdutos.setText("Produtos");
        JMnuConsulProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnuConsulProdutosActionPerformed(evt);
            }
        });
        jMnuConsultas.add(JMnuConsulProdutos);

        JMnuConsulVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        JMnuConsulVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/132300_open_file_icon.png"))); // NOI18N
        JMnuConsulVendas.setMnemonic('v');
        JMnuConsulVendas.setText("Vendas");
        JMnuConsulVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnuConsulVendasActionPerformed(evt);
            }
        });
        jMnuConsultas.add(JMnuConsulVendas);

        jMenuBar3.add(jMnuConsultas);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 438, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios JDlgUsuarios = new JDlgUsuarios(this, true);
        JDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuarioActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        JDlgProduto JDlgProduto = new JDlgProduto(this, true);
        JDlgProduto.setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void JMnuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnuCadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMnuCadastrosActionPerformed

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        // TODO add your handling code here:
        JDlgClientes JDlgClientes = new JDlgClientes(this, true);
        JDlgClientes.setVisible(true);
        
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JDlgIngredientes JDlgIngredientes = new JDlgIngredientes(this, true);
        JDlgIngredientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jBtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUsuariosActionPerformed
        // TODO add your handling code here:
        jMnuUsuarioActionPerformed(null);
        
    }//GEN-LAST:event_jBtnUsuariosActionPerformed

    private void jBtnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProdutosActionPerformed
        // TODO add your handling code here:
         jMnuProdutosActionPerformed(null);
    }//GEN-LAST:event_jBtnProdutosActionPerformed

    private void JMnuConsulClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnuConsulClientesActionPerformed
        // TODO add your handling code here:
        JDlgConsultaClientes JDlgConsultaClientes = new JDlgConsultaClientes(this, true);
        JDlgConsultaClientes.setVisible(true);

    }//GEN-LAST:event_JMnuConsulClientesActionPerformed

    private void JMnuConsulIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnuConsulIngredientesActionPerformed
        // TODO add your handling code here:
        JDlgConsultaIngredientes JDlgConsultaIngredientes = new JDlgConsultaIngredientes(this, true);
        JDlgConsultaIngredientes.setVisible(true);
    }//GEN-LAST:event_JMnuConsulIngredientesActionPerformed

    private void JMnuConsulProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnuConsulProdutosActionPerformed
        // TODO add your handling code here:
        JDlgConsultaProdutos JDlgConsultaProdutos = new JDlgConsultaProdutos(this, true);
        JDlgConsultaProdutos.setVisible(true);
    }//GEN-LAST:event_JMnuConsulProdutosActionPerformed

    private void JMnuConsulVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnuConsulVendasActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendas JDlgConsultaVendas = new JDlgConsultaVendas(this, true);
        JDlgConsultaVendas.setVisible(true);
    }//GEN-LAST:event_JMnuConsulVendasActionPerformed

    private void jBtnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendasActionPerformed
        // TODO add your handling code here:
           jMnuVendasActionPerformed(null);
    }//GEN-LAST:event_jBtnVendasActionPerformed

    private void jBtnConsulProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsulProdutoActionPerformed
        // TODO add your handling code here:
         JMnuConsulProdutosActionPerformed(null);
    }//GEN-LAST:event_jBtnConsulProdutoActionPerformed

    private void jBtnConsulVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsulVendasActionPerformed
        // TODO add your handling code here:
         JMnuConsulVendasActionPerformed(null);
    }//GEN-LAST:event_jBtnConsulVendasActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
        // TODO add your handling code here:
         JDlgVendas JDlgVendas = new JDlgVendas(this, true);
        JDlgVendas.setVisible(true);
    }//GEN-LAST:event_jMnuVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMnuCadastros;
    private javax.swing.JMenuItem JMnuConsulClientes;
    private javax.swing.JMenuItem JMnuConsulIngredientes;
    private javax.swing.JMenuItem JMnuConsulProdutos;
    private javax.swing.JMenuItem JMnuConsulVendas;
    private javax.swing.JMenu JMnuMovimentos;
    private javax.swing.JButton jBtnConsulProduto;
    private javax.swing.JButton jBtnConsulVendas;
    private javax.swing.JButton jBtnProdutos;
    private javax.swing.JButton jBtnUsuarios;
    private javax.swing.JButton jBtnVendas;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenu jMnuConsultas;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuario;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
