package bean;
// Generated 11/10/2025 16:22:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LgsClientes generated by hbm2java
 */
@Entity
@Table(name="lgs_clientes"
    ,catalog="db_luiz_silvero"
)
public class LgsClientes  implements java.io.Serializable {


     private int lgsIdClientes;
     private String lgsNome;
     private String lgsCpf;
     private String lgsTelefone;
     private String lgsEmail;
     private String lgsEndereco;
     private String lgsCidade;
     private String lgsEstado;
     private String lgsCep;
     private Date lgsDatanascimento;
     private String lgsSenha;
     private String lgsStatuscliente;
     private String lgsObservacoes;
     private String lgsNivel;
     private String lgsAtivo;

    public LgsClientes() {
    }

	
    public LgsClientes(int lgsIdClientes, String lgsNome, String lgsCpf, String lgsEndereco, String lgsCidade, String lgsEstado, Date lgsDatanascimento, String lgsSenha, String lgsNivel) {
        this.lgsIdClientes = lgsIdClientes;
        this.lgsNome = lgsNome;
        this.lgsCpf = lgsCpf;
        this.lgsEndereco = lgsEndereco;
        this.lgsCidade = lgsCidade;
        this.lgsEstado = lgsEstado;
        this.lgsDatanascimento = lgsDatanascimento;
        this.lgsSenha = lgsSenha;
        this.lgsNivel = lgsNivel;
    }
    public LgsClientes(int lgsIdClientes, String lgsNome, String lgsCpf, String lgsTelefone, String lgsEmail, String lgsEndereco, String lgsCidade, String lgsEstado, String lgsCep, Date lgsDatanascimento, String lgsSenha, String lgsStatuscliente, String lgsObservacoes, String lgsNivel, String lgsAtivo, Set lgsVendases) {
       this.lgsIdClientes = lgsIdClientes;
       this.lgsNome = lgsNome;
       this.lgsCpf = lgsCpf;
       this.lgsTelefone = lgsTelefone;
       this.lgsEmail = lgsEmail;
       this.lgsEndereco = lgsEndereco;
       this.lgsCidade = lgsCidade;
       this.lgsEstado = lgsEstado;
       this.lgsCep = lgsCep;
       this.lgsDatanascimento = lgsDatanascimento;
       this.lgsSenha = lgsSenha;
       this.lgsStatuscliente = lgsStatuscliente;
       this.lgsObservacoes = lgsObservacoes;
       this.lgsNivel = lgsNivel;
       this.lgsAtivo = lgsAtivo;
       
    }
   
     @Id 

    
    @Column(name="lgs_id_clientes", unique=true, nullable=false)
    public int getLgsIdClientes() {
        return this.lgsIdClientes;
    }
    
    public void setLgsIdClientes(int lgsIdClientes) {
        this.lgsIdClientes = lgsIdClientes;
    }

    
    @Column(name="lgs_nome", nullable=false, length=45)
    public String getLgsNome() {
        return this.lgsNome;
    }
    
    public void setLgsNome(String lgsNome) {
        this.lgsNome = lgsNome;
    }

    
    @Column(name="lgs_cpf", nullable=false, length=14)
    public String getLgsCpf() {
        return this.lgsCpf;
    }
    
    public void setLgsCpf(String lgsCpf) {
        this.lgsCpf = lgsCpf;
    }

    
    @Column(name="lgs_telefone", length=16)
    public String getLgsTelefone() {
        return this.lgsTelefone;
    }
    
    public void setLgsTelefone(String lgsTelefone) {
        this.lgsTelefone = lgsTelefone;
    }

    
    @Column(name="lgs_email", length=90)
    public String getLgsEmail() {
        return this.lgsEmail;
    }
    
    public void setLgsEmail(String lgsEmail) {
        this.lgsEmail = lgsEmail;
    }

    
    @Column(name="lgs_endereco", nullable=false, length=45)
    public String getLgsEndereco() {
        return this.lgsEndereco;
    }
    
    public void setLgsEndereco(String lgsEndereco) {
        this.lgsEndereco = lgsEndereco;
    }

    
    @Column(name="lgs_cidade", nullable=false, length=45)
    public String getLgsCidade() {
        return this.lgsCidade;
    }
    
    public void setLgsCidade(String lgsCidade) {
        this.lgsCidade = lgsCidade;
    }

    
    @Column(name="lgs_estado", nullable=false, length=2)
    public String getLgsEstado() {
        return this.lgsEstado;
    }
    
    public void setLgsEstado(String lgsEstado) {
        this.lgsEstado = lgsEstado;
    }

    
    @Column(name="lgs_cep", length=9)
    public String getLgsCep() {
        return this.lgsCep;
    }
    
    public void setLgsCep(String lgsCep) {
        this.lgsCep = lgsCep;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lgs_datanascimento", nullable=false, length=10)
    public Date getLgsDatanascimento() {
        return this.lgsDatanascimento;
    }
    
    public void setLgsDatanascimento(Date lgsDatanascimento) {
        this.lgsDatanascimento = lgsDatanascimento;
    }

    
    @Column(name="lgs_senha", nullable=false, length=100)
    public String getLgsSenha() {
        return this.lgsSenha;
    }
    
    public void setLgsSenha(String lgsSenha) {
        this.lgsSenha = lgsSenha;
    }

    
    @Column(name="lgs_statuscliente", length=1)
    public String getLgsStatuscliente() {
        return this.lgsStatuscliente;
    }
    
    public void setLgsStatuscliente(String lgsStatuscliente) {
        this.lgsStatuscliente = lgsStatuscliente;
    }

    
    @Column(name="lgs_observacoes", length=100)
    public String getLgsObservacoes() {
        return this.lgsObservacoes;
    }
    
    public void setLgsObservacoes(String lgsObservacoes) {
        this.lgsObservacoes = lgsObservacoes;
    }

    
    @Column(name="lgs_nivel", nullable=false, length=3)
    public String getLgsNivel() {
        return this.lgsNivel;
    }
    
    public void setLgsNivel(String lgsNivel) {
        this.lgsNivel = lgsNivel;
    }

    
    @Column(name="lgs_ativo", length=1)
    public String getLgsAtivo() {
        return this.lgsAtivo;
    }
    
    public void setLgsAtivo(String lgsAtivo) {
        this.lgsAtivo = lgsAtivo;
    }




}


