package bean;
// Generated 11/10/2025 16:22:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LgsIngredientes generated by hbm2java
 */
@Entity
@Table(name="lgs_ingredientes"
    ,catalog="db_luiz_silvero"
)
public class LgsIngredientes  implements java.io.Serializable {


     private int lgsIdIngredientes;
     private String lgsNome;
     private String lgsCategoria;
     private String lgsArmazenamento;
     private Date lgsDataValidade;
     private int lgsQuantidadeEstoque;
     private String lgsUnidadeMedida;

    public LgsIngredientes() {
    }

	public LgsIngredientes(int lgsIdIngredientes) {
        this.lgsIdIngredientes = lgsIdIngredientes;
    }
    public LgsIngredientes(int lgsIdIngredientes, String lgsNome, String lgsCategoria, String lgsArmazenamento, Date lgsDataValidade, int lgsQuantidadeEstoque, String lgsUnidadeMedida) {
        this.lgsIdIngredientes = lgsIdIngredientes;
        this.lgsNome = lgsNome;
        this.lgsCategoria = lgsCategoria;
        this.lgsArmazenamento = lgsArmazenamento;
        this.lgsDataValidade = lgsDataValidade;
        this.lgsQuantidadeEstoque = lgsQuantidadeEstoque;
        this.lgsUnidadeMedida = lgsUnidadeMedida;
    }
    public LgsIngredientes(int lgsIdIngredientes, String lgsNome, String lgsCategoria, String lgsArmazenamento, Date lgsDataValidade, int lgsQuantidadeEstoque, String lgsUnidadeMedida, Set lgsProdutos) {
       this.lgsIdIngredientes = lgsIdIngredientes;
       this.lgsNome = lgsNome;
       this.lgsCategoria = lgsCategoria;
       this.lgsArmazenamento = lgsArmazenamento;
       this.lgsDataValidade = lgsDataValidade;
       this.lgsQuantidadeEstoque = lgsQuantidadeEstoque;
       this.lgsUnidadeMedida = lgsUnidadeMedida;
    }
   
     @Id 

    
    @Column(name="lgs_id_ingredientes", unique=true, nullable=false)
    public int getLgsIdIngredientes() {
        return this.lgsIdIngredientes;
    }
    
    public void setLgsIdIngredientes(int lgsIdIngredientes) {
        this.lgsIdIngredientes = lgsIdIngredientes;
    }

    
    @Column(name="lgs_nome", nullable=false, length=55)
    public String getLgsNome() {
        return this.lgsNome;
    }
    
    public void setLgsNome(String lgsNome) {
        this.lgsNome = lgsNome;
    }

    
    @Column(name="lgs_categoria", nullable=false, length=45)
    public String getLgsCategoria() {
        return this.lgsCategoria;
    }
    
    public void setLgsCategoria(String lgsCategoria) {
        this.lgsCategoria = lgsCategoria;
    }

    
    @Column(name="lgs_armazenamento", nullable=false, length=45)
    public String getLgsArmazenamento() {
        return this.lgsArmazenamento;
    }
    
    public void setLgsArmazenamento(String lgsArmazenamento) {
        this.lgsArmazenamento = lgsArmazenamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lgs_dataValidade", nullable=false, length=10)
    public Date getLgsDataValidade() {
        return this.lgsDataValidade;
    }
    
    public void setLgsDataValidade(Date lgsDataValidade) {
        this.lgsDataValidade = lgsDataValidade;
    }

    
    @Column(name="lgs_quantidadeEstoque", nullable=false)
    public int getLgsQuantidadeEstoque() {
        return this.lgsQuantidadeEstoque;
    }
    
    public void setLgsQuantidadeEstoque(int lgsQuantidadeEstoque) {
        this.lgsQuantidadeEstoque = lgsQuantidadeEstoque;
    }

    
    @Column(name="lgs_unidadeMedida", nullable=false, length=10)
    public String getLgsUnidadeMedida() {
        return this.lgsUnidadeMedida;
    }
    
    public void setLgsUnidadeMedida(String lgsUnidadeMedida) {
        this.lgsUnidadeMedida = lgsUnidadeMedida;
    }


    @Override
    public String toString() {
        return this.lgsNome;
    }





}


