package bean;
// Generated 17/09/2025 10:12:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LgsProduto generated by hbm2java
 */
@Entity
@Table(name="lgs_produto"
    ,catalog="db_luiz_silvero"
)
public class LgsProduto  implements java.io.Serializable {


     private int lgsIdProduto;
     private LgsIngredientes lgsIngredientes;
     private String lgsNome;
     private String lgsDescricao;
     private BigDecimal lgsPreco;
     private String lgsCategoria;
     private String lgsComentario;
     private Set lgsVendasprodutos = new HashSet(0);

    public LgsProduto() {
    }

	
    public LgsProduto(int lgsIdProduto, LgsIngredientes lgsIngredientes, String lgsNome, BigDecimal lgsPreco, String lgsCategoria) {
        this.lgsIdProduto = lgsIdProduto;
        this.lgsIngredientes = lgsIngredientes;
        this.lgsNome = lgsNome;
        this.lgsPreco = lgsPreco;
        this.lgsCategoria = lgsCategoria;
    }
    public LgsProduto(int lgsIdProduto, LgsIngredientes lgsIngredientes, String lgsNome, String lgsDescricao, BigDecimal lgsPreco, String lgsCategoria, String lgsComentario, Set lgsVendasprodutos) {
       this.lgsIdProduto = lgsIdProduto;
       this.lgsIngredientes = lgsIngredientes;
       this.lgsNome = lgsNome;
       this.lgsDescricao = lgsDescricao;
       this.lgsPreco = lgsPreco;
       this.lgsCategoria = lgsCategoria;
       this.lgsComentario = lgsComentario;
       this.lgsVendasprodutos = lgsVendasprodutos;
    }
   
     @Id 

    
    @Column(name="lgs_id_Produto", unique=true, nullable=false)
    public int getLgsIdProduto() {
        return this.lgsIdProduto;
    }
    
    public void setLgsIdProduto(int lgsIdProduto) {
        this.lgsIdProduto = lgsIdProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lgs_fk_ingredientes", nullable=false)
    public LgsIngredientes getLgsIngredientes() {
        return this.lgsIngredientes;
    }
    
    public void setLgsIngredientes(LgsIngredientes lgsIngredientes) {
        this.lgsIngredientes = lgsIngredientes;
    }

    
    @Column(name="lgs_nome", nullable=false, length=45)
    public String getLgsNome() {
        return this.lgsNome;
    }
    
    public void setLgsNome(String lgsNome) {
        this.lgsNome = lgsNome;
    }

    
    @Column(name="lgs_descricao", length=45)
    public String getLgsDescricao() {
        return this.lgsDescricao;
    }
    
    public void setLgsDescricao(String lgsDescricao) {
        this.lgsDescricao = lgsDescricao;
    }

    
    @Column(name="lgs_preco", nullable=false, precision=10)
    public BigDecimal getLgsPreco() {
        return this.lgsPreco;
    }
    
    public void setLgsPreco(BigDecimal lgsPreco) {
        this.lgsPreco = lgsPreco;
    }

    
    @Column(name="lgs_categoria", nullable=false, length=45)
    public String getLgsCategoria() {
        return this.lgsCategoria;
    }
    
    public void setLgsCategoria(String lgsCategoria) {
        this.lgsCategoria = lgsCategoria;
    }

    
    @Column(name="lgs_comentario", length=90)
    public String getLgsComentario() {
        return this.lgsComentario;
    }
    
    public void setLgsComentario(String lgsComentario) {
        this.lgsComentario = lgsComentario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lgsProduto")
    public Set getLgsVendasprodutos() {
        return this.lgsVendasprodutos;
    }
    
    public void setLgsVendasprodutos(Set lgsVendasprodutos) {
        this.lgsVendasprodutos = lgsVendasprodutos;
    }




}


