package bean;
// Generated 11/10/2025 16:22:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LgsUsuario generated by hbm2java
 */
@Entity
@Table(name="lgs_usuario"
    ,catalog="db_luiz_silvero"
)
public class LgsUsuario  implements java.io.Serializable {


     private int lgsIdUsuario;
     private String lgsNome;
     private String lgsSenha;
     private String lgsApelido;
     private String lgsCpf;
     private Date lgsDataNascimento;
     private int lgsNivel;
     private String lgsAtivo;

    public LgsUsuario() {
    }

	
    public LgsUsuario(int lgsIdUsuario, String lgsNome, String lgsCpf, int lgsNivel) {
        this.lgsIdUsuario = lgsIdUsuario;
        this.lgsNome = lgsNome;
        this.lgsCpf = lgsCpf;
        this.lgsNivel = lgsNivel;
    }
    public LgsUsuario(int lgsIdUsuario, String lgsNome, String lgsSenha, String lgsApelido, String lgsCpf, Date lgsDataNascimento, int lgsNivel, String lgsAtivo, Set lgsVendases) {
       this.lgsIdUsuario = lgsIdUsuario;
       this.lgsNome = lgsNome;
       this.lgsSenha = lgsSenha;
       this.lgsApelido = lgsApelido;
       this.lgsCpf = lgsCpf;
       this.lgsDataNascimento = lgsDataNascimento;
       this.lgsNivel = lgsNivel;
       this.lgsAtivo = lgsAtivo;
    }
   
     @Id 

    
    @Column(name="lgs_id_usuario", unique=true, nullable=false)
    public int getLgsIdUsuario() {
        return this.lgsIdUsuario;
    }
    
    public void setLgsIdUsuario(int lgsIdUsuario) {
        this.lgsIdUsuario = lgsIdUsuario;
    }

    
    @Column(name="lgs_nome", nullable=false, length=90)
    public String getLgsNome() {
        return this.lgsNome;
    }
    
    public void setLgsNome(String lgsNome) {
        this.lgsNome = lgsNome;
    }

    
    @Column(name="lgs_senha", length=100)
    public String getLgsSenha() {
        return this.lgsSenha;
    }
    
    public void setLgsSenha(String lgsSenha) {
        this.lgsSenha = lgsSenha;
    }

    
    @Column(name="lgs_apelido", length=100)
    public String getLgsApelido() {
        return this.lgsApelido;
    }
    
    public void setLgsApelido(String lgsApelido) {
        this.lgsApelido = lgsApelido;
    }

    
    @Column(name="lgs_cpf", nullable=false, length=14)
    public String getLgsCpf() {
        return this.lgsCpf;
    }
    
    public void setLgsCpf(String lgsCpf) {
        this.lgsCpf = lgsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lgs_dataNascimento", length=10)
    public Date getLgsDataNascimento() {
        return this.lgsDataNascimento;
    }
    
    public void setLgsDataNascimento(Date lgsDataNascimento) {
        this.lgsDataNascimento = lgsDataNascimento;
    }

    
    @Column(name="lgs_nivel", nullable=false)
    public int getLgsNivel() {
        return this.lgsNivel;
    }
    
    public void setLgsNivel(int lgsNivel) {
        this.lgsNivel = lgsNivel;
    }

    
    @Column(name="lgs_ativo", length=1)
    public String getLgsAtivo() {
        return this.lgsAtivo;
    }
    
    public void setLgsAtivo(String lgsAtivo) {
        this.lgsAtivo = lgsAtivo;
    }






}


