package bean;
// Generated 17/09/2025 10:12:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LgsVendas generated by hbm2java
 */
@Entity
@Table(name="lgs_vendas"
    ,catalog="db_luiz_silvero"
)
public class LgsVendas  implements java.io.Serializable {


     private int lgsIdVendas;
     private LgsClientes lgsClientes;
     private LgsUsuario lgsUsuario;
     private Date lgsDataVendas;
     private Integer lgsFormaPagamento;
     private Double lgsTotal;
     private Character lgsStatusVenda;
     private Set lgsVendasprodutos = new HashSet(0);

    public LgsVendas() {
    }

	
    public LgsVendas(int lgsIdVendas, LgsClientes lgsClientes, LgsUsuario lgsUsuario) {
        this.lgsIdVendas = lgsIdVendas;
        this.lgsClientes = lgsClientes;
        this.lgsUsuario = lgsUsuario;
    }
    public LgsVendas(int lgsIdVendas, LgsClientes lgsClientes, LgsUsuario lgsUsuario, Date lgsDataVendas, Integer lgsFormaPagamento, Double lgsTotal, Character lgsStatusVenda, Set lgsVendasprodutos) {
       this.lgsIdVendas = lgsIdVendas;
       this.lgsClientes = lgsClientes;
       this.lgsUsuario = lgsUsuario;
       this.lgsDataVendas = lgsDataVendas;
       this.lgsFormaPagamento = lgsFormaPagamento;
       this.lgsTotal = lgsTotal;
       this.lgsStatusVenda = lgsStatusVenda;
       this.lgsVendasprodutos = lgsVendasprodutos;
    }
   
     @Id 

    
    @Column(name="lgs_id_vendas", unique=true, nullable=false)
    public int getLgsIdVendas() {
        return this.lgsIdVendas;
    }
    
    public void setLgsIdVendas(int lgsIdVendas) {
        this.lgsIdVendas = lgsIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lgs_fk_clientes", nullable=false)
    public LgsClientes getLgsClientes() {
        return this.lgsClientes;
    }
    
    public void setLgsClientes(LgsClientes lgsClientes) {
        this.lgsClientes = lgsClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lgs_fk_usuario", nullable=false)
    public LgsUsuario getLgsUsuario() {
        return this.lgsUsuario;
    }
    
    public void setLgsUsuario(LgsUsuario lgsUsuario) {
        this.lgsUsuario = lgsUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lgs_dataVendas", length=10)
    public Date getLgsDataVendas() {
        return this.lgsDataVendas;
    }
    
    public void setLgsDataVendas(Date lgsDataVendas) {
        this.lgsDataVendas = lgsDataVendas;
    }

    
    @Column(name="lgs_formaPagamento")
    public Integer getLgsFormaPagamento() {
        return this.lgsFormaPagamento;
    }
    
    public void setLgsFormaPagamento(Integer lgsFormaPagamento) {
        this.lgsFormaPagamento = lgsFormaPagamento;
    }

    
    @Column(name="lgs_total", precision=22, scale=0)
    public Double getLgsTotal() {
        return this.lgsTotal;
    }
    
    public void setLgsTotal(Double lgsTotal) {
        this.lgsTotal = lgsTotal;
    }

    
    @Column(name="lgs_status_venda", length=1)
    public Character getLgsStatusVenda() {
        return this.lgsStatusVenda;
    }
    
    public void setLgsStatusVenda(Character lgsStatusVenda) {
        this.lgsStatusVenda = lgsStatusVenda;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lgsVendas")
    public Set getLgsVendasprodutos() {
        return this.lgsVendasprodutos;
    }
    
    public void setLgsVendasprodutos(Set lgsVendasprodutos) {
        this.lgsVendasprodutos = lgsVendasprodutos;
    }




}


