package bean;
// Generated 11/10/2025 16:22:09 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LgsVendasproduto generated by hbm2java
 */
@Entity
@Table(name="lgs_vendasproduto"
    ,catalog="db_luiz_silvero"
)
public class LgsVendasproduto  implements java.io.Serializable {


     private int lgsIdVendasproduto;
     private LgsProduto lgsProduto;
     private LgsVendas lgsVendas;
     private int lgsQuantidadeProduto;
     private Double lgsValorUnitario;
     private Double lgsDesconto;

    public LgsVendasproduto() {
    }

    public LgsVendasproduto(int lgsIdVendasproduto, LgsProduto lgsProduto, LgsVendas lgsVendas, int lgsQuantidadeProduto, Double lgsValorUnitario, Double lgsDesconto) {
       this.lgsIdVendasproduto = lgsIdVendasproduto;
       this.lgsProduto = lgsProduto;
       this.lgsVendas = lgsVendas;
       this.lgsQuantidadeProduto = lgsQuantidadeProduto;
       this.lgsValorUnitario = lgsValorUnitario;
       this.lgsDesconto = lgsDesconto;
    }
   
     @Id 

    
    @Column(name="lgs_id_vendasproduto", unique=true, nullable=false)
    public int getLgsIdVendasproduto() {
        return this.lgsIdVendasproduto;
    }
    
    public void setLgsIdVendasproduto(int lgsIdVendasproduto) {
        this.lgsIdVendasproduto = lgsIdVendasproduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lgs_fk_produto", nullable=false)
    public LgsProduto getLgsProduto() {
        return this.lgsProduto;
    }
    
    public void setLgsProduto(LgsProduto lgsProduto) {
        this.lgsProduto = lgsProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lgs_fk_vendas", nullable=false)
    public LgsVendas getLgsVendas() {
        return this.lgsVendas;
    }
    
    public void setLgsVendas(LgsVendas lgsVendas) {
        this.lgsVendas = lgsVendas;
    }

    
    @Column(name="lgs_quantidadeProduto", nullable=false)
    public int getLgsQuantidadeProduto() {
        return this.lgsQuantidadeProduto;
    }
    
    public void setLgsQuantidadeProduto(int lgsQuantidadeProduto) {
        this.lgsQuantidadeProduto = lgsQuantidadeProduto;
    }

    
    @Column(name="lgs_valorUnitario", nullable=false, precision=10)
    public Double getLgsValorUnitario() {
        return this.lgsValorUnitario;
    }
    
    public void setLgsValorUnitario(Double lgsValorUnitario) {
        this.lgsValorUnitario = lgsValorUnitario;
    }

    
    @Column(name="lgs_desconto", nullable=false, precision=10)
    public Double getLgsDesconto() {
        return this.lgsDesconto;
    }
    
    public void setLgsDesconto(Double lgsDesconto) {
        this.lgsDesconto = lgsDesconto;
    }




}


